version: '3.7'

services:
  prometheus:
    image: prom/prometheus:latest
    hostname: prometheus
    restart: always
    volumes:
      - ./conf.d/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    expose:
      - 9090
    ports:
      - 9090:9090


  grafana:
    image: grafana/grafana:9.1.2-ubuntu
    hostname: grafana
    ports:
      - "3000:3000"
    volumes:
      - "grafana_data:/var/lib/grafana"


  json-exporter:
    image: quay.io/prometheuscommunity/json-exporter
    hostname: json-exporter
    ports:
      - "7979:7979"
    volumes:
      - ./conf.d/json-exporter.yml:/config.yml:ro


  simple_api:
    image: simple_api:latest
    hostname: api
    ports:
      - "5000:5000"

    
volumes:
  prometheus_data: {}
  grafana_data: {}