version: '3.7'

services:
  elasticsearch:
    image: elasticsearch:8.4.0
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elk
    environment:
      discovery.type: single-node

  logstash:
    image: logstash:8.4.0
    ports:
      - "5044:5044"
      - "50000:50000/tcp"
      - "50000:50000/udp"
      - "9600:9600"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    image: kibana:8.4.0
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:
  elk:
    driver: bridge