version: '3.7'

services:
  node-exporter:
    image: prom/node-exporter:latest
    hostname: node-exporter
    restart: always
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100
    ports:
      - "9100:9100"
    networks:
      - monitoring
  
  prometheus:
    image: prom/prometheus:latest
    hostname: prometheus
    restart: always
    volumes:
      - ./conf.d/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    expose:
      - 9090
    ports:
      - 9090:9090
    networks:
      - monitoring
  grafana:
    image: grafana/grafana:9.1.1-ubuntu
    hostname: grafana
    ports:
      - "3000:3000"
    volumes:
      - "grafana_data:/var/lib/grafana"
    networks:
      - monitoring
  pushgateway:
    image: prom/pushgateway
    hostname: pushgateway
    ports:
      - "9091:9091"
    networks:
      - monitoring
  influxdb:
    image: influxdb:latest
    hostname: influxdb
    volumes:
      - ./influx:/root/.influxdb2
    ports:
      - "8086:8086"
    networks:
      - monitoring
  telegraf:
    image: telegraf:latest
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
    ports:
      - "8125:8125"
    networks:
      - monitoring
    
volumes:
  prometheus_data: {}
  grafana_data: {}
networks:
  monitoring:
    driver: bridge