global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 10s
    static_configs:
    - targets: ["prometheus:9090"]

  - job_name: "node"
    scrape_interval: 10s
    static_configs:
    - targets: ["node-exporter:9100"]
  - job_name: "pushgateway"
    honor_labels: true
    scrape_interval: 10s
    static_configs:
    - targets: ["pushgateway:9091"]
