global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 10s
    static_configs:
    - targets: ["prometheus:9090"]

  - job_name: json-exporter
    scrape_interval: 10s
    scrape_timeout: 8s
    metrics_path: "/probe"
    static_configs:
      - targets:
          - http://couchdb:5984/test/health
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__address__]
        regex: ^http.+currency=([A-Z]{3})
        action: replace
        target_label: currency
        replacement: ${1}
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: json-exporter:7979

